// AUTO-GENERIERT von scripts/gen-name-lang-base.mjs — nicht von Hand editieren.
// Quelle: data/name-lists/namen_lexicon_<locale>.xml (kuratierte Lexika).
// Gefalteter Name → Herkunftssprache für den Azure-`<lang>`-Pfad. Mehrdeutige
// Namen (in mehreren Sprachen) sind bewusst NICHT enthalten (deutscher Default).
import type { NameLang } from "./transliterate";

export const NAME_LANG_BASE: Map<string, NameLang> = new Map([
  ["aadhya", "in"],
  ["aadhya narayanan", "in"],
  ["aadhya rajput", "in"],
  ["aadhya tandon", "in"],
  ["aanya", "in"],
  ["aarav", "in"],
  ["aarti", "in"],
  ["aarti banerjee", "in"],
  ["aarti mishra", "in"],
  ["aarti ramachandran", "in"],
  ["aarti ranganathan", "in"],
  ["abdul", "ms"],
  ["abdul hassan", "ms"],
  ["abdul musa", "ms"],
  ["abdullah", "ms"],
  ["acar", "tr"],
  ["acharya", "in"],
  ["acosta", "es"],
  ["adam chrzanowski", "pl"],
  ["adam ridzuan", "ms"],
  ["adamczyk", "pl"],
  ["adamski", "pl"],
  ["aditi", "in"],
  ["aditi kapoor", "in"],
  ["aditi narayanan", "in"],
  ["aditi rao", "in"],
  ["aditi verma", "in"],
  ["aditya", "in"],
  ["adnan", "ms"],
  ["adrian", "es"],
  ["adrian reyes", "es"],
  ["adrien", "fr"],
  ["agarwal", "in"],
  ["aggarwal", "in"],
  ["agnieszka", "pl"],
  ["agnieszka kaczmarczyk", "pl"],
  ["agueda", "es"],
  ["agueda lozano", "es"],
  ["aguilar", "es"],
  ["aguilera", "es"],
  ["ahmad", "ms"],
  ["ahmad anuar", "ms"],
  ["ahmet", "tr"],
  ["ahmet aslan", "tr"],
  ["ahmet yilmaz", "tr"],
  ["aiman", "ms"],
  ["aiman lah", "ms"],
  ["aiman umar", "ms"],
  ["aiman wan", "ms"],
  ["ainhoa", "es"],
  ["ainhoa gutierrez", "es"],
  ["ainhoa pastor", "es"],
  ["aishwarya", "in"],
  ["aishwarya desai", "in"],
  ["aishwarya goel", "in"],
  ["aishwarya parikh", "in"],
  ["aisyah", "ms"],
  ["aitor", "es"],
  ["aitor marquez", "es"],
  ["akash", "in"],
  ["akgun", "tr"],
  ["akin", "tr"],
  ["akkaya", "tr"],
  ["akman", "tr"],
  ["akova", "tr"],
  ["aksoy", "tr"],
  ["aktas", "tr"],
  ["akturk", "tr"],
  ["akyildiz", "tr"],
  ["alain", "fr"],
  ["alba", "es"],
  ["alba campos", "es"],
  ["alba mendoza", "es"],
  ["alba vidal", "es"],
  ["alberto", "es"],
  ["aleeya", "ms"],
  ["aleeya pawanchik", "ms"],
  ["aleeya tengku", "ms"],
  ["alejandro", "es"],
  ["alejandro escudero", "es"],
  ["alejandro marquez", "es"],
  ["alejandro quintana", "es"],
  ["aleksandra", "pl"],
  ["aleksandra maciejewski", "pl"],
  ["aleksandra pietrzak", "pl"],
  ["aleksandra walczak", "pl"],
  ["alexandre", "fr"],
  ["alexandre baron", "fr"],
  ["alexandre maillard", "fr"],
  ["alexandre perez", "fr"],
  ["aleyna", "tr"],
  ["aleyna aytac", "tr"],
  ["ali camlica", "tr"],
  ["ali dahlan", "ms"],
  ["ali koc", "tr"],
  ["ali salleh", "ms"],
  ["ali tahir", "ms"],
  ["alia", "ms"],
  ["alia dollah", "ms"],
  ["alia sapuan", "ms"],
  ["alice", "fr"],
  ["alice leclercq", "fr"],
  ["alice roche", "fr"],
  ["alicja", "pl"],
  ["alicja wilk", "pl"],
  ["alonso", "es"],
  ["alvarez", "es"],
  ["alvaro", "es"],
  ["alvaro rubio", "es"],
  ["amelia", "pl"],
  ["amelia krol", "pl"],
  ["amin", "ms"],
  ["aminah", "ms"],
  ["aminah mohamed", "ms"],
  ["aminah othman", "ms"],
  ["amir", "ms"],
  ["amit", "in"],
  ["amparo", "es"],
  ["amparo iglesias", "es"],
  ["ana", "es"],
  ["ana soler", "es"],
  ["anand", "in"],
  ["anantharaman", "in"],
  ["ananya", "in"],
  ["ananya krishnamurthy", "in"],
  ["ananya pandya", "in"],
  ["andre", "fr"],
  ["andre boyer", "fr"],
  ["andrea", "es"],
  ["andres", "es"],
  ["andrzej", "pl"],
  ["angel", "es"],
  ["angel roldan", "es"],
  ["angel roman", "es"],
  ["angela", "es"],
  ["angela bernal", "es"],
  ["anika", "in"],
  ["anika kaur", "in"],
  ["anika sawant", "in"],
  ["anika srinivasan", "in"],
  ["aniket", "in"],
  ["aniket vaidyanathan", "in"],
  ["anil", "in"],
  ["anil chowdhury", "in"],
  ["anil yadav", "in"],
  ["anita", "in"],
  ["anita brar", "in"],
  ["anita kamath", "in"],
  ["anita sekhon", "in"],
  ["anita toor", "in"],
  ["anjali", "in"],
  ["anjali agarwal", "in"],
  ["anjali kapoor", "in"],
  ["anjali mann", "in"],
  ["anjali rajan", "in"],
  ["ankit", "in"],
  ["ankit bedi", "in"],
  ["ankit chaudhary", "in"],
  ["ankit janardhanan", "in"],
  ["ankit raghavan", "in"],
  ["ankit shah", "in"],
  ["anna", "pl"],
  ["anne", "fr"],
  ["anne jacquet", "fr"],
  ["antoine", "fr"],
  ["antoine renault", "fr"],
  ["antoni", "pl"],
  ["antoni bak", "pl"],
  ["antoni maciejewski", "pl"],
  ["antonia", "es"],
  ["antonia gil", "es"],
  ["antonia marquez", "es"],
  ["antonio", "es"],
  ["antonio fernandez", "es"],
  ["antonio salas", "es"],
  ["anuar", "ms"],
  ["anwar", "ms"],
  ["anwar sapuan", "ms"],
  ["anwar wahyu", "ms"],
  ["aparicio", "es"],
  ["apte", "in"],
  ["aqil", "ms"],
  ["aqilah", "ms"],
  ["aqilah ghazali", "ms"],
  ["aqilah zin", "ms"],
  ["arda", "tr"],
  ["arda akova", "tr"],
  ["arda senturk", "tr"],
  ["arias", "es"],
  ["arjun", "in"],
  ["arjun chatterjee", "in"],
  ["arjun dubey", "in"],
  ["arjun gopalakrishnan", "in"],
  ["arjun sen", "in"],
  ["arnaud", "fr"],
  ["arora", "in"],
  ["arshad", "ms"],
  ["arslan", "tr"],
  ["arthur", "fr"],
  ["arun", "in"],
  ["arun jain", "in"],
  ["arun sharma", "in"],
  ["aryan", "in"],
  ["asha", "in"],
  ["asha nair", "in"],
  ["ashok", "in"],
  ["ashok deshpande", "in"],
  ["ashok kulkarni", "in"],
  ["ashok venkatesan", "in"],
  ["aslan", "tr"],
  ["asli", "tr"],
  ["asri", "ms"],
  ["atharv", "in"],
  ["atharv bose", "in"],
  ["atharv lakshmanan", "in"],
  ["atharv parikh", "in"],
  ["aubert", "fr"],
  ["aubry", "fr"],
  ["audrey", "fr"],
  ["audrey lemaire", "fr"],
  ["audrey roy", "fr"],
  ["aurelie", "fr"],
  ["aurelie aubert", "fr"],
  ["aurelie bertin", "fr"],
  ["avci", "tr"],
  ["aydemir", "tr"],
  ["aydin", "tr"],
  ["aydinli", "tr"],
  ["aydogan", "tr"],
  ["ayhan", "tr"],
  ["ayik", "tr"],
  ["ayse", "tr"],
  ["ayse demiroz", "tr"],
  ["ayse gumus", "tr"],
  ["aytac", "tr"],
  ["aytekin", "tr"],
  ["aytemiz", "tr"],
  ["aziz", "ms"],
  ["aziz othman", "ms"],
  ["aziz pawanchik", "ms"],
  ["azlan", "ms"],
  ["azman", "ms"],
  ["azman qasim", "ms"],
  ["bahar", "tr"],
  ["bahar tekin", "tr"],
  ["baharin", "ms"],
  ["bailly", "fr"],
  ["bains", "in"],
  ["bajaj", "in"],
  ["bak", "pl"],
  ["bakar", "ms"],
  ["bakar majid", "ms"],
  ["bakri", "ms"],
  ["bala", "in"],
  ["bala gupta", "in"],
  ["bala phadke", "in"],
  ["balasubramanian", "in"],
  ["balci", "tr"],
  ["balqis", "ms"],
  ["banerjee", "in"],
  ["bansal", "in"],
  ["baran", "pl"],
  ["barbara", "pl"],
  ["barbier", "fr"],
  ["baris", "tr"],
  ["baris ozen", "tr"],
  ["baris ozgul", "tr"],
  ["baris turan", "tr"],
  ["baris yildan", "tr"],
  ["baron", "fr"],
  ["barre", "fr"],
  ["bartłomiej", "pl"],
  ["bartłomiej michalski", "pl"],
  ["bartłomiej mikołajczyk", "pl"],
  ["bartłomiej zajac", "pl"],
  ["basir", "ms"],
  ["batrisyia", "ms"],
  ["batrisyia basir", "ms"],
  ["bayram", "tr"],
  ["beata", "pl"],
  ["beata duda", "pl"],
  ["beatriz", "es"],
  ["beatriz caballero", "es"],
  ["beatriz molina", "es"],
  ["beatriz morales", "es"],
  ["beatriz soto", "es"],
  ["bedi", "in"],
  ["bednarczyk", "pl"],
  ["bednarek", "pl"],
  ["begona", "es"],
  ["begona gimeno", "es"],
  ["begona perez", "es"],
  ["benitez", "es"],
  ["benjamin", "fr"],
  ["benjamin bertrand", "fr"],
  ["benjamin herve", "fr"],
  ["benjamin muller", "fr"],
  ["benoit", "fr"],
  ["beren", "tr"],
  ["beren keskin", "tr"],
  ["beren ozbek", "tr"],
  ["beren yildan", "tr"],
  ["berger", "fr"],
  ["berk", "tr"],
  ["berk cakmak", "tr"],
  ["berk can", "tr"],
  ["berk cetiner", "tr"],
  ["berk sen", "tr"],
  ["bermudez", "es"],
  ["bernal", "es"],
  ["bernard", "fr"],
  ["bernard bailly", "fr"],
  ["bernard garnier", "fr"],
  ["bernard maillard", "fr"],
  ["bernard royer", "fr"],
  ["bertin", "fr"],
  ["bertrand", "fr"],
  ["besson", "fr"],
  ["bhagat", "in"],
  ["bhagwat", "in"],
  ["bhardwaj", "in"],
  ["bhat", "in"],
  ["bhatia", "in"],
  ["bhattacharya", "in"],
  ["bhavna", "in"],
  ["bhavna dhillon", "in"],
  ["bhavna lakshmanan", "in"],
  ["bielecki", "pl"],
  ["bilge", "tr"],
  ["bilge ozgur", "tr"],
  ["bilgin", "tr"],
  ["blanc", "fr"],
  ["blanchard", "fr"],
  ["blanco", "es"],
  ["bogdan", "pl"],
  ["bogdan sikorski", "pl"],
  ["bogdan urbanski", "pl"],
  ["bonnet", "fr"],
  ["borhan", "ms"],
  ["borhan kassim", "ms"],
  ["borhan omar", "ms"],
  ["borhan tajuddin", "ms"],
  ["borkowski", "pl"],
  ["borowski", "pl"],
  ["bose", "in"],
  ["boucher", "fr"],
  ["bourgeois", "fr"],
  ["bouvier", "fr"],
  ["boyer", "fr"],
  ["bozena", "pl"],
  ["bozena czarnecki", "pl"],
  ["bozena lis", "pl"],
  ["bozena malinowski", "pl"],
  ["bozena szczesny", "pl"],
  ["bozkurt", "tr"],
  ["brar", "in"],
  ["bravo", "es"],
  ["breton", "fr"],
  ["brigitte", "fr"],
  ["brun", "fr"],
  ["brunet", "fr"],
  ["bruno", "fr"],
  ["bruno chevalier", "fr"],
  ["bruno faure", "fr"],
  ["brzezinski", "pl"],
  ["bulut", "tr"],
  ["burak", "tr"],
  ["burak dogan", "tr"],
  ["burak gul", "tr"],
  ["burak tuncel", "tr"],
  ["burcu", "tr"],
  ["burcu ayik", "tr"],
  ["burcu demirbas", "tr"],
  ["busra", "tr"],
  ["busra demircan", "tr"],
  ["busra gunes", "tr"],
  ["busra sari", "tr"],
  ["busra sarioglu", "tr"],
  ["busra soysal", "tr"],
  ["błaszczyk", "pl"],
  ["caballero", "es"],
  ["cabrera", "es"],
  ["caglar", "tr"],
  ["cakal", "tr"],
  ["caki", "tr"],
  ["cakir", "tr"],
  ["cakirca", "tr"],
  ["cakiroglu", "tr"],
  ["cakmak", "tr"],
  ["cakmakci", "tr"],
  ["calis", "tr"],
  ["calvo", "es"],
  ["camacho", "es"],
  ["camille", "fr"],
  ["camille maillard", "fr"],
  ["camille poirier", "fr"],
  ["camlica", "tr"],
  ["campos", "es"],
  ["can", "tr"],
  ["can cakirca", "tr"],
  ["can demiroz", "tr"],
  ["can duman", "tr"],
  ["cano", "es"],
  ["cansu", "tr"],
  ["carla", "es"],
  ["carla rodriguez", "es"],
  ["carlos", "es"],
  ["carlos cano", "es"],
  ["carlos carvajal", "es"],
  ["carlos saez", "es"],
  ["carlos santiago", "es"],
  ["carmen", "es"],
  ["carmen soto", "es"],
  ["carmona", "es"],
  ["carolina", "es"],
  ["caroline", "fr"],
  ["caroline barre", "fr"],
  ["caron", "fr"],
  ["carpentier", "fr"],
  ["carrasco", "es"],
  ["carre", "fr"],
  ["carrillo", "es"],
  ["carvajal", "es"],
  ["castillo", "es"],
  ["castro", "es"],
  ["catalina", "es"],
  ["catherine", "fr"],
  ["catherine barbier", "fr"],
  ["cedric", "fr"],
  ["cedric renard", "fr"],
  ["celia", "es"],
  ["celia flores", "es"],
  ["celik", "tr"],
  ["celine", "fr"],
  ["celine david", "fr"],
  ["cem", "tr"],
  ["cem aytekin", "tr"],
  ["cem cetin", "tr"],
  ["cem karabulut", "tr"],
  ["cem tas", "tr"],
  ["cem yetkin", "tr"],
  ["cemre", "tr"],
  ["cemre cakmakci", "tr"],
  ["cemre dogan", "tr"],
  ["cemre ozdemir", "tr"],
  ["cemre sezer", "tr"],
  ["ceren", "tr"],
  ["ceren sezer", "tr"],
  ["cetin", "tr"],
  ["cetiner", "tr"],
  ["cetinkaya", "tr"],
  ["cetintas", "tr"],
  ["cevik", "tr"],
  ["chandrasekaran", "in"],
  ["chantal", "fr"],
  ["chantal mercier", "fr"],
  ["chantal michel", "fr"],
  ["charles", "fr"],
  ["charlotte", "fr"],
  ["charlotte guyot", "fr"],
  ["charpentier", "fr"],
  ["chatterjee", "in"],
  ["chaudhary", "in"],
  ["chauhan", "in"],
  ["che", "ms"],
  ["cheema", "in"],
  ["chevalier", "fr"],
  ["chik", "ms"],
  ["chloe", "fr"],
  ["chloe lefebvre", "fr"],
  ["chmielewski", "pl"],
  ["chopra", "in"],
  ["chowdhury", "in"],
  ["christian", "fr"],
  ["christine", "fr"],
  ["christine picard", "fr"],
  ["christine robert", "fr"],
  ["christophe", "fr"],
  ["christophe louis", "fr"],
  ["christophe meyer", "fr"],
  ["chrzanowski", "pl"],
  ["cicek", "tr"],
  ["cieslak", "pl"],
  ["ciftci", "tr"],
  ["cinar", "tr"],
  ["clara", "fr"],
  ["clara charpentier", "fr"],
  ["clara marchal", "fr"],
  ["claude", "fr"],
  ["claude bailly", "fr"],
  ["claude francois", "fr"],
  ["claude gaillard", "fr"],
  ["claude gerard", "fr"],
  ["claudia", "es"],
  ["claudia delgado", "es"],
  ["claudia herrero", "es"],
  ["claudia munoz", "es"],
  ["claudine", "fr"],
  ["claudine charpentier", "fr"],
  ["clement", "fr"],
  ["clement boucher", "fr"],
  ["clement jacquet", "fr"],
  ["coban", "tr"],
  ["colak", "tr"],
  ["colin", "fr"],
  ["collet", "fr"],
  ["concepcion", "es"],
  ["concepcion aparicio", "es"],
  ["concepcion escudero", "es"],
  ["conde", "es"],
  ["consuelo", "es"],
  ["consuelo torres", "es"],
  ["cordero", "es"],
  ["corinne", "fr"],
  ["corinne brunet", "fr"],
  ["corinne dufour", "fr"],
  ["corinne morel", "fr"],
  ["corinne robert", "fr"],
  ["cortes", "es"],
  ["coskun", "tr"],
  ["cousin", "fr"],
  ["crespo", "es"],
  ["cristina", "es"],
  ["cristina franco", "es"],
  ["cristina hernandez", "es"],
  ["cristina merino", "es"],
  ["cruz", "es"],
  ["cuesta", "es"],
  ["cuevas", "es"],
  ["czajka", "pl"],
  ["czarnecki", "pl"],
  ["czech", "pl"],
  ["czerwinski", "pl"],
  ["czesław", "pl"],
  ["czesław dabrowski", "pl"],
  ["czesław zakrzewski", "pl"],
  ["czesława", "pl"],
  ["czesława gorski", "pl"],
  ["czesława stepien", "pl"],
  ["dabrowski", "pl"],
  ["dahlan", "ms"],
  ["dahlia", "ms"],
  ["dahlia che", "ms"],
  ["daim", "ms"],
  ["daim majid", "ms"],
  ["daim nawawi", "ms"],
  ["daim osman", "ms"],
  ["damia", "ms"],
  ["damia usman", "ms"],
  ["damian", "pl"],
  ["damian szczesny", "pl"],
  ["damien", "fr"],
  ["damla", "tr"],
  ["damla yagiz", "tr"],
  ["daniel carvajal", "es"],
  ["daniel gaillard", "fr"],
  ["daniel paris", "fr"],
  ["daniel rubio", "es"],
  ["daniel santos", "es"],
  ["danish", "ms"],
  ["danish dahlan", "ms"],
  ["danish daud", "ms"],
  ["danish kamal", "ms"],
  ["danish mat", "ms"],
  ["danish sani", "ms"],
  ["danuta", "pl"],
  ["danuta gajda", "pl"],
  ["danuta kwiatkowski", "pl"],
  ["danuta mazur", "pl"],
  ["danuta mroz", "pl"],
  ["danuta wrobel", "pl"],
  ["danuta zieba", "pl"],
  ["das", "in"],
  ["daud", "ms"],
  ["dave", "in"],
  ["david herrera", "es"],
  ["dawid", "pl"],
  ["dawid lewandowski", "pl"],
  ["deepa", "in"],
  ["deepa agarwal", "in"],
  ["deepa balasubramanian", "in"],
  ["deepa pandya", "in"],
  ["deepak", "in"],
  ["deepak modi", "in"],
  ["deepak pandey", "in"],
  ["defne", "tr"],
  ["defne erdem", "tr"],
  ["defne karaagac", "tr"],
  ["delgado", "es"],
  ["delphine", "fr"],
  ["delphine carre", "fr"],
  ["delphine leblanc", "fr"],
  ["delphine rey", "fr"],
  ["demir", "tr"],
  ["demiral", "tr"],
  ["demirbas", "tr"],
  ["demircan", "tr"],
  ["demirci", "tr"],
  ["demirel", "tr"],
  ["demiroz", "tr"],
  ["demirtas", "tr"],
  ["denis", "fr"],
  ["denise", "fr"],
  ["denise brunet", "fr"],
  ["denise gaillard", "fr"],
  ["deniz", "tr"],
  ["deniz karaca", "tr"],
  ["deniz kurt", "tr"],
  ["derya", "tr"],
  ["derya unal", "tr"],
  ["desai", "in"],
  ["deschamps", "fr"],
  ["deshpande", "in"],
  ["dev", "in"],
  ["dev chowdhury", "in"],
  ["dev jain", "in"],
  ["dhillon", "in"],
  ["diaz", "es"],
  ["didier", "fr"],
  ["didier aubry", "fr"],
  ["didier collet", "fr"],
  ["didier duval", "fr"],
  ["didier fernandez", "fr"],
  ["didier garcia", "fr"],
  ["diego", "es"],
  ["diego pastor", "es"],
  ["diez", "es"],
  ["dilek", "tr"],
  ["dilek sen", "tr"],
  ["dinesh", "in"],
  ["divya", "in"],
  ["divya jha", "in"],
  ["divya mehta", "in"],
  ["divya srinivasan", "in"],
  ["divya srivastava", "in"],
  ["diya", "in"],
  ["diya gupta", "in"],
  ["diya menon", "in"],
  ["diya patil", "in"],
  ["diya shah", "in"],
  ["diya toor", "in"],
  ["dogan", "tr"],
  ["dollah", "ms"],
  ["dolores", "es"],
  ["dolores marin", "es"],
  ["dolores navarro", "es"],
  ["dolores sanchez", "es"],
  ["domanski", "pl"],
  ["dominguez", "es"],
  ["dominik", "pl"],
  ["dominik brzezinski", "pl"],
  ["dominik chmielewski", "pl"],
  ["dominik czajka", "pl"],
  ["dominik dudek", "pl"],
  ["dominik krol", "pl"],
  ["dominik zakrzewski", "pl"],
  ["dominik zielinski", "pl"],
  ["dominique", "fr"],
  ["dominique bernard", "fr"],
  ["dorota", "pl"],
  ["dorota wawrzyniak", "pl"],
  ["doruk", "tr"],
  ["doruk bulut", "tr"],
  ["dubey", "in"],
  ["dubois", "fr"],
  ["duda", "pl"],
  ["dudek", "pl"],
  ["dufour", "fr"],
  ["duman", "tr"],
  ["dumas", "fr"],
  ["dumont", "fr"],
  ["dupont", "fr"],
  ["dupuis", "fr"],
  ["dupuy", "fr"],
  ["duran", "es"],
  ["durand", "fr"],
  ["dutta", "in"],
  ["duval", "fr"],
  ["dziedzic", "pl"],
  ["ebru", "tr"],
  ["ebru turan", "tr"],
  ["eduardo", "es"],
  ["eduardo vera", "es"],
  ["edward", "pl"],
  ["edward michalski", "pl"],
  ["edward tomczak", "pl"],
  ["efe", "tr"],
  ["effendi", "ms"],
  ["ela", "tr"],
  ["ela aktas", "tr"],
  ["ela calis", "tr"],
  ["ela cetinkaya", "tr"],
  ["elena", "es"],
  ["elena alvarez", "es"],
  ["elena vicente", "es"],
  ["elif", "tr"],
  ["elif coban", "tr"],
  ["elif tas", "tr"],
  ["elina", "ms"],
  ["elina chik", "ms"],
  ["elina zakaria", "ms"],
  ["elodie", "fr"],
  ["elodie blanchard", "fr"],
  ["elodie rey", "fr"],
  ["elzbieta", "pl"],
  ["embong", "ms"],
  ["emilia", "pl"],
  ["emilia karpinski", "pl"],
  ["emilia sikorski", "pl"],
  ["emilie", "fr"],
  ["emilio", "es"],
  ["emilio mendez", "es"],
  ["emilio vidal", "es"],
  ["emine", "tr"],
  ["emine bulut", "tr"],
  ["emine cakirca", "tr"],
  ["emine ozgul", "tr"],
  ["emine sonmez", "tr"],
  ["emine yorulmaz", "tr"],
  ["emma", "fr"],
  ["emma robert", "fr"],
  ["emre", "tr"],
  ["encarnacion", "es"],
  ["enrique", "es"],
  ["enrique galan", "es"],
  ["enrique sanz", "es"],
  ["enzo", "fr"],
  ["enzo leger", "fr"],
  ["enzo sanchez", "fr"],
  ["erdem", "tr"],
  ["erdogan", "tr"],
  ["eren", "tr"],
  ["eren kilic", "tr"],
  ["eric", "fr"],
  ["eric benoit", "fr"],
  ["eric lefebvre", "fr"],
  ["eryna", "ms"],
  ["eryna idris", "ms"],
  ["eryna obeng", "ms"],
  ["eryna wati", "ms"],
  ["esa", "ms"],
  ["escudero", "es"],
  ["esperanza", "es"],
  ["esperanza gimeno", "es"],
  ["espinosa", "es"],
  ["esra", "tr"],
  ["esra kose", "tr"],
  ["esteban", "es"],
  ["esther", "es"],
  ["esther espinosa", "es"],
  ["eugeniusz", "pl"],
  ["eugeniusz dziedzic", "pl"],
  ["eugeniusz pawlik", "pl"],
  ["eugeniusz rutkowski", "pl"],
  ["eva", "es"],
  ["eva ortiz", "es"],
  ["eva palomo", "es"],
  ["evelyne", "fr"],
  ["ewa", "pl"],
  ["eylul", "tr"],
  ["eylul arslan", "tr"],
  ["eylul cetintas", "tr"],
  ["eylul erdem", "tr"],
  ["eylul sarac", "tr"],
  ["fabre", "fr"],
  ["fabrice", "fr"],
  ["fabrice roussel", "fr"],
  ["fadzil", "ms"],
  ["faisal", "ms"],
  ["farah", "ms"],
  ["farah ismail", "ms"],
  ["farah lokman", "ms"],
  ["farah osman", "ms"],
  ["farah umar", "ms"],
  ["faris", "ms"],
  ["fatimah", "ms"],
  ["fatimah iliyas", "ms"],
  ["fatma", "tr"],
  ["faure", "fr"],
  ["fauzi", "ms"],
  ["fauzi bakar", "ms"],
  ["felipe", "es"],
  ["ferda", "tr"],
  ["ferda akman", "tr"],
  ["ferda yilmaz", "tr"],
  ["fernando", "es"],
  ["fernando fuentes", "es"],
  ["fernando pereira", "es"],
  ["ferrer", "es"],
  ["fikri", "ms"],
  ["filip", "pl"],
  ["filip lis", "pl"],
  ["filip skowronski", "pl"],
  ["filip sobczak", "pl"],
  ["fleury", "fr"],
  ["florence", "fr"],
  ["florence bailly", "fr"],
  ["florence renault", "fr"],
  ["flores", "es"],
  ["florian", "fr"],
  ["florian faure", "fr"],
  ["florian rey", "fr"],
  ["fontaine", "fr"],
  ["fournier", "fr"],
  ["francisca", "es"],
  ["francisca ojeda", "es"],
  ["francisca sanz", "es"],
  ["francisco", "es"],
  ["francisco dominguez", "es"],
  ["franciszek", "pl"],
  ["franciszek bak", "pl"],
  ["franco", "es"],
  ["francois", "fr"],
  ["francoise", "fr"],
  ["francoise fournier", "fr"],
  ["frederic", "fr"],
  ["frederic charpentier", "fr"],
  ["frederic perez", "fr"],
  ["fuentes", "es"],
  ["furkan", "tr"],
  ["furkan ozkok", "tr"],
  ["furkan sen", "tr"],
  ["furkan senturk", "tr"],
  ["gabriel castro", "es"],
  ["gabriela", "pl"],
  ["gabriela mucha", "pl"],
  ["gabriela włodarczyk", "pl"],
  ["gaikwad", "in"],
  ["gaillard", "fr"],
  ["gajda", "pl"],
  ["gajewski", "pl"],
  ["galan", "es"],
  ["gall", "fr"],
  ["gallardo", "es"],
  ["gallego", "es"],
  ["gamze", "tr"],
  ["ganesh", "in"],
  ["ganesh bajaj", "in"],
  ["ganesh dutta", "in"],
  ["ganesh kumar", "in"],
  ["ganesh parthasarathy", "in"],
  ["ganesh tiwari", "in"],
  ["gani", "ms"],
  ["garg", "in"],
  ["garnier", "fr"],
  ["garrido", "es"],
  ["gaurav", "in"],
  ["gauthier", "fr"],
  ["gautier", "fr"],
  ["geeta", "in"],
  ["geeta krishnamurthy", "in"],
  ["geeta kulkarni", "in"],
  ["genevieve", "fr"],
  ["genevieve charpentier", "fr"],
  ["genevieve dupuis", "fr"],
  ["genevieve lambert", "fr"],
  ["genevieve marchal", "fr"],
  ["genowefa", "pl"],
  ["genowefa błaszczyk", "pl"],
  ["georges", "fr"],
  ["georges goff", "fr"],
  ["gerard", "fr"],
  ["gerard boyer", "fr"],
  ["gerard lecomte", "fr"],
  ["gerard olivier", "fr"],
  ["gerard perez", "fr"],
  ["gerard robert", "fr"],
  ["gerard simon", "fr"],
  ["germain", "fr"],
  ["ghani", "ms"],
  ["ghani anuar", "ms"],
  ["ghazali", "ms"],
  ["ghosh", "in"],
  ["gil", "es"],
  ["gill", "in"],
  ["gimeno", "es"],
  ["girard", "fr"],
  ["giraud", "fr"],
  ["gizem", "tr"],
  ["gloria", "es"],
  ["gloria pena", "es"],
  ["gloria reyes", "es"],
  ["goel", "in"],
  ["goff", "fr"],
  ["gokhale", "in"],
  ["gomez", "es"],
  ["gonul", "tr"],
  ["gonul cakal", "tr"],
  ["gonul cetiner", "tr"],
  ["gonul sari", "tr"],
  ["gonzalez", "es"],
  ["gonzalo", "es"],
  ["gonzalo rivas", "es"],
  ["gopalakrishnan", "in"],
  ["gorski", "pl"],
  ["govindarajan", "in"],
  ["goyal", "in"],
  ["grabowski", "pl"],
  ["grazyna", "pl"],
  ["grazyna sobanski", "pl"],
  ["grazyna wawrzyniak", "pl"],
  ["grewal", "in"],
  ["grzegorz", "pl"],
  ["grzegorzewski", "pl"],
  ["guclu", "tr"],
  ["guerin", "fr"],
  ["guerrero", "es"],
  ["guillaume", "fr"],
  ["guillaume charpentier", "fr"],
  ["guillaume collet", "fr"],
  ["guillaume muller", "fr"],
  ["guillaume robin", "fr"],
  ["guillaume vincent", "fr"],
  ["guillermo", "es"],
  ["guillermo ramirez", "es"],
  ["guillermo torres", "es"],
  ["guillot", "fr"],
  ["guler", "tr"],
  ["gullu", "tr"],
  ["gumus", "tr"],
  ["gunduz", "tr"],
  ["gunes", "tr"],
  ["gungor", "tr"],
  ["gupta", "in"],
  ["gutierrez", "es"],
  ["guvenc", "tr"],
  ["guyot", "fr"],
  ["głowacki", "pl"],
  ["hafidz", "ms"],
  ["hafidz jamal", "ms"],
  ["hafidz pendek", "ms"],
  ["hafiz", "ms"],
  ["hafiz salleh", "ms"],
  ["hakim", "ms"],
  ["hakim rahman", "ms"],
  ["hakim shariff", "ms"],
  ["halil", "tr"],
  ["halil aytekin", "tr"],
  ["halil karabulut", "tr"],
  ["halil tosun", "tr"],
  ["halim", "ms"],
  ["halim ahmad", "ms"],
  ["halim hamzah", "ms"],
  ["halim jais", "ms"],
  ["halim nasrudin", "ms"],
  ["halim noor", "ms"],
  ["halim talib", "ms"],
  ["halina", "pl"],
  ["halina kruk", "pl"],
  ["halina walczak", "pl"],
  ["hamid", "ms"],
  ["hamzah", "ms"],
  ["hamzah jalil", "ms"],
  ["hamzah puteh", "ms"],
  ["hamzah talib", "ms"],
  ["hana", "ms"],
  ["hana wahid", "ms"],
  ["hanafi", "ms"],
  ["handan", "tr"],
  ["handan akova", "tr"],
  ["handan aydin", "tr"],
  ["hande", "tr"],
  ["hande toker", "tr"],
  ["hande ucar", "tr"],
  ["hanife", "tr"],
  ["hanife aslan", "tr"],
  ["hanife celik", "tr"],
  ["hanife karacay", "tr"],
  ["hanna", "pl"],
  ["harith", "ms"],
  ["harith ong", "ms"],
  ["harsh", "in"],
  ["harsh dutta", "in"],
  ["harun", "ms"],
  ["hasan", "tr"],
  ["hasan avci", "tr"],
  ["hasan karaagac", "tr"],
  ["hashim", "ms"],
  ["hassan", "ms"],
  ["hatice", "tr"],
  ["hatice coskun", "tr"],
  ["hatice erdogan", "tr"],
  ["hatice kilic", "tr"],
  ["havva", "tr"],
  ["havva acar", "tr"],
  ["havva ozcelik", "tr"],
  ["haziq", "ms"],
  ["haziq basir", "ms"],
  ["haziq fikri", "ms"],
  ["haziq othman", "ms"],
  ["haziq wahyu", "ms"],
  ["hegde", "in"],
  ["helena", "pl"],
  ["helena sobolewski", "pl"],
  ["helene", "fr"],
  ["helene charpentier", "fr"],
  ["henri", "fr"],
  ["henri louis", "fr"],
  ["henry", "fr"],
  ["henryk", "pl"],
  ["henryk cieslak", "pl"],
  ["henryk krawczyk", "pl"],
  ["henryk sokołowski", "pl"],
  ["henryk szymanski", "pl"],
  ["heredia", "es"],
  ["hernandez", "es"],
  ["herrera", "es"],
  ["herrero", "es"],
  ["herve", "fr"],
  ["hidalgo", "es"],
  ["hidayah", "ms"],
  ["hidayah ahmad", "ms"],
  ["hidayah jalil", "ms"],
  ["hidayah ridzuan", "ms"],
  ["hubert", "fr"],
  ["huet", "fr"],
  ["hugo fontaine", "fr"],
  ["hugo ortega", "es"],
  ["hurtado", "es"],
  ["huseyin", "tr"],
  ["huseyin akman", "tr"],
  ["huseyin gungor", "tr"],
  ["huseyin yagiz", "tr"],
  ["hussin", "ms"],
  ["ibanez", "es"],
  ["ibrahim akyildiz", "tr"],
  ["ibrahim ozcelik", "tr"],
  ["ibrahim yagcilar", "tr"],
  ["idris", "ms"],
  ["idris dollah", "ms"],
  ["idris tajuddin", "ms"],
  ["iffah", "ms"],
  ["iffah abdullah", "ms"],
  ["iffah iliyas", "ms"],
  ["iffah razak", "ms"],
  ["iglesias", "es"],
  ["ignacio", "es"],
  ["ignacio camacho", "es"],
  ["ignacio fuentes", "es"],
  ["ignacio vazquez", "es"],
  ["iliyas", "ms"],
  ["iman", "ms"],
  ["iman nawawi", "ms"],
  ["iman rahim", "ms"],
  ["imran", "ms"],
  ["ines esteban", "es"],
  ["ines gil", "es"],
  ["ines legrand", "fr"],
  ["ines marchand", "fr"],
  ["ines mata", "es"],
  ["inmaculada", "es"],
  ["inmaculada silva", "es"],
  ["insyirah", "ms"],
  ["insyirah asri", "ms"],
  ["irem", "tr"],
  ["irena", "pl"],
  ["irena jarosz", "pl"],
  ["irena kubiak", "pl"],
  ["irena sosnowski", "pl"],
  ["irene", "es"],
  ["irene vera", "es"],
  ["irfan", "ms"],
  ["irfan jaafar", "ms"],
  ["irfan nik", "ms"],
  ["irfan sulaiman", "ms"],
  ["irfan yaacob", "ms"],
  ["isabel", "es"],
  ["isabel cortes", "es"],
  ["isabel gallardo", "es"],
  ["isabelle", "fr"],
  ["isabelle gauthier", "fr"],
  ["isabelle olivier", "fr"],
  ["ishaan", "in"],
  ["ishaan hegde", "in"],
  ["ishaan nair", "in"],
  ["ishaan phadke", "in"],
  ["ishita", "in"],
  ["ishita chaudhary", "in"],
  ["ishita kalyanaraman", "in"],
  ["ishita lakshmanan", "in"],
  ["ishita pillai", "in"],
  ["iskandar", "ms"],
  ["iskandar asri", "ms"],
  ["iskandar ghazali", "ms"],
  ["iskandar pawanchik", "ms"],
  ["ismail gullu", "tr"],
  ["ismail hassan", "ms"],
  ["ivan", "es"],
  ["ivan heredia", "es"],
  ["ivan mateo", "es"],
  ["iwona", "pl"],
  ["iyengar", "in"],
  ["iyer", "in"],
  ["jaafar", "ms"],
  ["jabłonski", "pl"],
  ["jacques", "fr"],
  ["jacques dupont", "fr"],
  ["jacques roussel", "fr"],
  ["jacquet", "fr"],
  ["jade", "fr"],
  ["jade duval", "fr"],
  ["jadhav", "in"],
  ["jadwiga", "pl"],
  ["jadwiga grzegorzewski", "pl"],
  ["jain", "in"],
  ["jais", "ms"],
  ["jakub", "pl"],
  ["jakub gajda", "pl"],
  ["jakub sienkiewicz", "pl"],
  ["jakubowski", "pl"],
  ["jalil", "ms"],
  ["jamal", "ms"],
  ["jamil", "ms"],
  ["jan", "pl"],
  ["jan malinowski", "pl"],
  ["jan nowakowski", "pl"],
  ["jan piotrowski", "pl"],
  ["jan sobanski", "pl"],
  ["janardhanan", "in"],
  ["janik", "pl"],
  ["janina", "pl"],
  ["janina kołodziejczyk", "pl"],
  ["janina sadowski", "pl"],
  ["janina sobczak", "pl"],
  ["jankowski", "pl"],
  ["jannah", "ms"],
  ["jannah basir", "ms"],
  ["jannah marican", "ms"],
  ["jannah nasir", "ms"],
  ["jannah wan", "ms"],
  ["janusz", "pl"],
  ["janusz kubiak", "pl"],
  ["janusz skowronski", "pl"],
  ["jarosz", "pl"],
  ["jasinski", "pl"],
  ["javier", "es"],
  ["javier campos", "es"],
  ["javier gallego", "es"],
  ["javier vazquez", "es"],
  ["jaworski", "pl"],
  ["jean", "fr"],
  ["jean fleury", "fr"],
  ["jean gaillard", "fr"],
  ["jerzy", "pl"],
  ["jerzy mikołajczyk", "pl"],
  ["jesus", "es"],
  ["jesus jimenez", "es"],
  ["jesus ortiz", "es"],
  ["jha", "in"],
  ["jimenez", "es"],
  ["joanna", "pl"],
  ["joanna kazmierczak", "pl"],
  ["joanna pawłowski", "pl"],
  ["joanna sobczak", "pl"],
  ["joaquin", "es"],
  ["joaquin campos", "es"],
  ["joaquin marin", "es"],
  ["johari", "ms"],
  ["johari harun", "ms"],
  ["johari obeng", "ms"],
  ["johari samad", "ms"],
  ["johari tajuddin", "ms"],
  ["joly", "fr"],
  ["jorge", "es"],
  ["jorge camacho", "es"],
  ["jorge carrasco", "es"],
  ["jorge flores", "es"],
  ["jorge sierra", "es"],
  ["jorge vallejo", "es"],
  ["jose", "es"],
  ["jose luis", "es"],
  ["jose luis gallego", "es"],
  ["jose luis vela", "es"],
  ["josefa", "es"],
  ["josefa carrillo", "es"],
  ["josefa munoz", "es"],
  ["josefa palomo", "es"],
  ["joshi", "in"],
  ["josiane", "fr"],
  ["josiane germain", "fr"],
  ["jozef", "pl"],
  ["jozef kazmierczak", "pl"],
  ["jozef kozioł", "pl"],
  ["jozef marciniak", "pl"],
  ["juan", "es"],
  ["juan palomo", "es"],
  ["jules", "fr"],
  ["jules boucher", "fr"],
  ["julia lopez", "es"],
  ["julie", "fr"],
  ["julie denis", "fr"],
  ["julien", "fr"],
  ["julien charles", "fr"],
  ["julien lacroix", "fr"],
  ["julien royer", "fr"],
  ["juliette", "fr"],
  ["juliette giraud", "fr"],
  ["justine", "fr"],
  ["justine lucas", "fr"],
  ["justine meunier", "fr"],
  ["justine moulin", "fr"],
  ["justine robert", "fr"],
  ["justine schneider", "fr"],
  ["justine vidal", "fr"],
  ["justyna", "pl"],
  ["justyna lipinski", "pl"],
  ["kaan", "tr"],
  ["kaan yoruk", "tr"],
  ["kabir", "in"],
  ["kabir hegde", "in"],
  ["kabir krishnamurthy", "in"],
  ["kabir sane", "in"],
  ["kaczmar", "pl"],
  ["kaczmarczyk", "pl"],
  ["kaczmarek", "pl"],
  ["kadir", "ms"],
  ["kahraman", "tr"],
  ["kale", "in"],
  ["kalinowski", "pl"],
  ["kalyanaraman", "in"],
  ["kamal", "ms"],
  ["kamarudin", "ms"],
  ["kamath", "in"],
  ["kamil", "pl"],
  ["kamil kaminski", "pl"],
  ["kamil kowalski", "pl"],
  ["kamil skowronski", "pl"],
  ["kamil wojcik", "pl"],
  ["kaminski", "pl"],
  ["kaplan", "tr"],
  ["kapoor", "in"],
  ["kara", "tr"],
  ["karaagac", "tr"],
  ["karabulut", "tr"],
  ["karaca", "tr"],
  ["karacay", "tr"],
  ["karadag", "tr"],
  ["karahan", "tr"],
  ["karaman", "tr"],
  ["karan", "in"],
  ["karan bains", "in"],
  ["karan chowdhury", "in"],
  ["karandikar", "in"],
  ["karatas", "tr"],
  ["karim", "ms"],
  ["karine", "fr"],
  ["karolina", "pl"],
  ["karolina jankowski", "pl"],
  ["karolina konieczny", "pl"],
  ["karpinski", "pl"],
  ["karthik", "in"],
  ["karthik dave", "in"],
  ["karthik kumar", "in"],
  ["karthik shetty", "in"],
  ["kashyap", "in"],
  ["kassim", "ms"],
  ["kassim gani", "ms"],
  ["kassim maarof", "ms"],
  ["katarzyna", "pl"],
  ["katarzyna lis", "pl"],
  ["kaur", "in"],
  ["kavya", "in"],
  ["kavya kamath", "in"],
  ["kavya patel", "in"],
  ["kavya ranganathan", "in"],
  ["kaya", "tr"],
  ["kazimierz", "pl"],
  ["kazimierz baran", "pl"],
  ["kazimierz gajewski", "pl"],
  ["kazimierz korzeniowski", "pl"],
  ["kazimierz lipinski", "pl"],
  ["kazimierz tomaszewski", "pl"],
  ["kazmierczak", "pl"],
  ["kemal", "tr"],
  ["kemal caki", "tr"],
  ["kemal sahin", "tr"],
  ["kerem", "tr"],
  ["kerem avci", "tr"],
  ["kerem unal", "tr"],
  ["keskin", "tr"],
  ["khadijah", "ms"],
  ["khadijah che", "ms"],
  ["khadijah rahman", "ms"],
  ["khadijah ridzuan", "ms"],
  ["khadijah yahya", "ms"],
  ["khadijah zabidi", "ms"],
  ["khaleeda", "ms"],
  ["khaleeda rashid", "ms"],
  ["khaleeda shariff", "ms"],
  ["khaleeda yakub", "ms"],
  ["khanna", "in"],
  ["khurana", "in"],
  ["kilic", "tr"],
  ["kinga", "pl"],
  ["klaudia", "pl"],
  ["klein", "fr"],
  ["klimek", "pl"],
  ["koc", "tr"],
  ["komal", "in"],
  ["komal das", "in"],
  ["komal kashyap", "in"],
  ["komal tandon", "in"],
  ["komal yadav", "in"],
  ["komur", "tr"],
  ["konieczny", "pl"],
  ["korkmaz", "tr"],
  ["korzeniowski", "pl"],
  ["kose", "tr"],
  ["kowalczyk", "pl"],
  ["kowalewski", "pl"],
  ["kowalski", "pl"],
  ["kozioł", "pl"],
  ["kozłowski", "pl"],
  ["kołodziej", "pl"],
  ["kołodziejczyk", "pl"],
  ["krawczyk", "pl"],
  ["krishna", "in"],
  ["krishna anand", "in"],
  ["krishna dave", "in"],
  ["krishna mishra", "in"],
  ["krishnamurthy", "in"],
  ["krishnan", "in"],
  ["krishnan chaudhary", "in"],
  ["kriti", "in"],
  ["kriti dhillon", "in"],
  ["kriti thakur", "in"],
  ["kriti vishwanathan", "in"],
  ["krol", "pl"],
  ["kruk", "pl"],
  ["krupa", "pl"],
  ["krystyna", "pl"],
  ["krystyna kalinowski", "pl"],
  ["krystyna kozłowski", "pl"],
  ["krzysztof", "pl"],
  ["krzysztof kaminski", "pl"],
  ["kubiak", "pl"],
  ["kubra", "tr"],
  ["kubra cetiner", "tr"],
  ["kucharczyk", "pl"],
  ["kucharski", "pl"],
  ["kulkarni", "in"],
  ["kumar", "in"],
  ["kurnaz", "tr"],
  ["kurt", "tr"],
  ["kus", "tr"],
  ["kustepe", "tr"],
  ["kutlu", "tr"],
  ["kwiatkowski", "pl"],
  ["lacroix", "fr"],
  ["lah", "ms"],
  ["laila", "ms"],
  ["lakshmanan", "in"],
  ["lakshmi", "in"],
  ["lakshmi chopra", "in"],
  ["lakshmi kale", "in"],
  ["lambert", "fr"],
  ["langlois", "fr"],
  ["lara", "es"],
  ["laskowski", "pl"],
  ["lata", "in"],
  ["lata more", "in"],
  ["lata sen", "in"],
  ["latif", "ms"],
  ["latif aziz", "ms"],
  ["latiff", "ms"],
  ["laurent", "fr"],
  ["laurent duval", "fr"],
  ["laurent martin", "fr"],
  ["laurent perrin", "fr"],
  ["le", "fr"],
  ["lea", "fr"],
  ["lea lopez", "fr"],
  ["leblanc", "fr"],
  ["lebrun", "fr"],
  ["leclerc", "fr"],
  ["leclercq", "fr"],
  ["lecomte", "fr"],
  ["lefebvre", "fr"],
  ["lefevre", "fr"],
  ["leger", "fr"],
  ["legrand", "fr"],
  ["lemaire", "fr"],
  ["lemoine", "fr"],
  ["lena", "pl"],
  ["lena mikołajczyk", "pl"],
  ["leo", "fr"],
  ["leon", "es"],
  ["leroux", "fr"],
  ["leroy", "fr"],
  ["leszek", "pl"],
  ["leszek sieradzki", "pl"],
  ["leveque", "fr"],
  ["lewandowski", "pl"],
  ["lewicki", "pl"],
  ["leyla", "tr"],
  ["leyla polat", "tr"],
  ["lim", "ms"],
  ["lipinski", "pl"],
  ["lis", "pl"],
  ["liyana", "ms"],
  ["liyana borhan", "ms"],
  ["liyana halim", "ms"],
  ["liyana rashid", "ms"],
  ["liyana sani", "ms"],
  ["lokman", "ms"],
  ["lokman effendi", "ms"],
  ["lokman tan", "ms"],
  ["lorena", "es"],
  ["lorena ponce", "es"],
  ["lorenzo", "es"],
  ["louis", "fr"],
  ["louis lopez", "fr"],
  ["louise", "fr"],
  ["louise carre", "fr"],
  ["louise langlois", "fr"],
  ["lozano", "es"],
  ["lucas", "fr"],
  ["lucas lemaire", "fr"],
  ["lucia", "es"],
  ["lucia garrido", "es"],
  ["lucia jimenez", "es"],
  ["lucia ojeda", "es"],
  ["lucie", "fr"],
  ["lucie boyer", "fr"],
  ["lucie millet", "fr"],
  ["luis", "es"],
  ["luis gimeno", "es"],
  ["luis ortega", "es"],
  ["luis velasco", "es"],
  ["luna", "es"],
  ["luqman", "ms"],
  ["luqman ismail", "ms"],
  ["luqman sani", "ms"],
  ["luqman umar", "ms"],
  ["maarof", "ms"],
  ["macias", "es"],
  ["maciejewski", "pl"],
  ["madeleine", "fr"],
  ["madeleine blanc", "fr"],
  ["magdalena", "pl"],
  ["magdalena jaworski", "pl"],
  ["magdalena mazur", "pl"],
  ["magdalena mroczek", "pl"],
  ["magdalena sikora", "pl"],
  ["mahadevan", "in"],
  ["mahesh", "in"],
  ["mahesh anantharaman", "in"],
  ["mahesh pandya", "in"],
  ["mahmud", "ms"],
  ["mahmud bakri", "ms"],
  ["maillard", "fr"],
  ["maisarah", "ms"],
  ["maisarah adnan", "ms"],
  ["maisarah daim", "ms"],
  ["maj", "pl"],
  ["maja", "pl"],
  ["maja kaczmarek", "pl"],
  ["majewski", "pl"],
  ["majid", "ms"],
  ["maldonado", "es"],
  ["malhotra", "in"],
  ["malinowski", "pl"],
  ["manan", "ms"],
  ["mani", "in"],
  ["mani anantharaman", "in"],
  ["mani cheema", "in"],
  ["mani kaur", "in"],
  ["mani pandey", "in"],
  ["mani shetty", "in"],
  ["mann", "in"],
  ["manoj", "in"],
  ["manon", "fr"],
  ["manon gautier", "fr"],
  ["manon royer", "fr"],
  ["mansor", "ms"],
  ["mansor dollah", "ms"],
  ["mansor lah", "ms"],
  ["mansor lim", "ms"],
  ["mansor musa", "ms"],
  ["manuel", "es"],
  ["manuel carrasco", "es"],
  ["manuel heredia", "es"],
  ["manuel herrero", "es"],
  ["manuel sanz", "es"],
  ["manuela", "es"],
  ["manuela roman", "es"],
  ["mar", "es"],
  ["marcel", "fr"],
  ["marcel blanchard", "fr"],
  ["marcel cousin", "fr"],
  ["marcel poirier", "fr"],
  ["marcel remy", "fr"],
  ["marchal", "fr"],
  ["marchand", "fr"],
  ["marcin", "pl"],
  ["marcin bielecki", "pl"],
  ["marcin gajda", "pl"],
  ["marcin sawicki", "pl"],
  ["marcin szymanski", "pl"],
  ["marciniak", "pl"],
  ["marcos", "es"],
  ["marek", "pl"],
  ["marek kruk", "pl"],
  ["marek mazur", "pl"],
  ["marek nowak", "pl"],
  ["marek nowakowski", "pl"],
  ["marek sosnowski", "pl"],
  ["maria dziedzic", "pl"],
  ["maria owczarek", "pl"],
  ["maria roldan", "es"],
  ["maria szczepaniak", "pl"],
  ["mariam", "ms"],
  ["mariam majid", "ms"],
  ["marican", "ms"],
  ["marie", "fr"],
  ["marie aubert", "fr"],
  ["marie lemoine", "fr"],
  ["marin", "es"],
  ["marina", "es"],
  ["marina diaz", "es"],
  ["marina trujillo", "es"],
  ["marine", "fr"],
  ["marine simon", "fr"],
  ["mario", "es"],
  ["mario vila", "es"],
  ["mariusz", "pl"],
  ["mariusz borkowski", "pl"],
  ["mariusz jankowski", "pl"],
  ["markowski", "pl"],
  ["marquez", "es"],
  ["marta merino", "es"],
  ["marta sobolewski", "pl"],
  ["marta vallejo", "es"],
  ["marta zalewski", "pl"],
  ["martin caballero", "es"],
  ["martin maldonado", "es"],
  ["martin sanz", "es"],
  ["martine", "fr"],
  ["martine robin", "fr"],
  ["marty", "fr"],
  ["maryam", "ms"],
  ["maryam razak", "ms"],
  ["maryam zahari", "ms"],
  ["marzena", "pl"],
  ["marzena owczarek", "pl"],
  ["masson", "fr"],
  ["mat", "ms"],
  ["mata", "es"],
  ["mateo", "es"],
  ["mateusz", "pl"],
  ["mateusz marciniak", "pl"],
  ["mateusz zieba", "pl"],
  ["mathieu", "fr"],
  ["mathilde", "fr"],
  ["mathilde maillard", "fr"],
  ["maxime", "fr"],
  ["maxime klein", "fr"],
  ["maya", "in"],
  ["mazur", "pl"],
  ["mazurek", "pl"],
  ["mazurkiewicz", "pl"],
  ["małgorzata", "pl"],
  ["małgorzata kalinowski", "pl"],
  ["małgorzata wroblewski", "pl"],
  ["medina", "es"],
  ["meera", "in"],
  ["meera bhattacharya", "in"],
  ["mehmet", "tr"],
  ["mehmet aytemiz", "tr"],
  ["mehmet dogan", "tr"],
  ["mehmet ozgur", "tr"],
  ["mehta", "in"],
  ["melek", "tr"],
  ["melek tunc", "tr"],
  ["menard", "fr"],
  ["mendez", "es"],
  ["mendoza", "es"],
  ["menon", "in"],
  ["mercier", "fr"],
  ["merino", "es"],
  ["mert", "tr"],
  ["merve", "tr"],
  ["merve cinar", "tr"],
  ["merve sezer", "tr"],
  ["meryem", "tr"],
  ["meunier", "fr"],
  ["meyer", "fr"],
  ["michalak", "pl"],
  ["michalski", "pl"],
  ["michał", "pl"],
  ["michał bednarek", "pl"],
  ["michel", "fr"],
  ["michel dumas", "fr"],
  ["michel schmitt", "fr"],
  ["miguel", "es"],
  ["miguel franco", "es"],
  ["miguel macias", "es"],
  ["mikołajczyk", "pl"],
  ["millet", "fr"],
  ["mira", "in"],
  ["mireille", "fr"],
  ["mireille brunet", "fr"],
  ["mirosław", "pl"],
  ["mirosław krawczyk", "pl"],
  ["mirosław marek", "pl"],
  ["mirosław przybylski", "pl"],
  ["mishra", "in"],
  ["mittal", "in"],
  ["modi", "in"],
  ["mohamed", "ms"],
  ["mohd", "ms"],
  ["mohd ujang", "ms"],
  ["molina", "es"],
  ["monica", "es"],
  ["monica alvarez", "es"],
  ["monica sanz", "es"],
  ["monika", "pl"],
  ["monika urbanski", "pl"],
  ["monika wawrzyniak", "pl"],
  ["monika wroblewski", "pl"],
  ["monique", "fr"],
  ["monique menard", "fr"],
  ["montero", "es"],
  ["montserrat", "es"],
  ["montserrat caballero", "es"],
  ["montserrat munoz", "es"],
  ["montserrat vega", "es"],
  ["mora", "es"],
  ["morales", "es"],
  ["more", "in"],
  ["moreau", "fr"],
  ["morel", "fr"],
  ["moreno", "es"],
  ["morin", "fr"],
  ["moulin", "fr"],
  ["moya", "es"],
  ["mroczek", "pl"],
  ["mroz", "pl"],
  ["mucha", "pl"],
  ["muhammad", "ms"],
  ["muhammad effendi", "ms"],
  ["muhammad lah", "ms"],
  ["muhammad yakub", "ms"],
  ["mukherjee", "in"],
  ["muller", "fr"],
  ["munevver", "tr"],
  ["munevver komur", "tr"],
  ["munoz", "es"],
  ["murat", "tr"],
  ["murat cakal", "tr"],
  ["murat gungor", "tr"],
  ["murthy", "in"],
  ["murugan", "in"],
  ["murugan kumar", "in"],
  ["murugan rao", "in"],
  ["musa", "ms"],
  ["mustafa", "tr"],
  ["mustafa cetin", "tr"],
  ["mustafa ozer", "tr"],
  ["mustafa yagcilar", "tr"],
  ["nadia", "ms"],
  ["nadia dahlan", "ms"],
  ["nadia marican", "ms"],
  ["nadia sapuan", "ms"],
  ["naidu", "in"],
  ["nair", "in"],
  ["najwa", "ms"],
  ["najwa jamal", "ms"],
  ["najwa lokman", "ms"],
  ["nandini", "in"],
  ["nandini goyal", "in"],
  ["narayanan", "in"],
  ["nasir", "ms"],
  ["nasir jalil", "ms"],
  ["nasir nik", "ms"],
  ["nasir samad", "ms"],
  ["nasrudin", "ms"],
  ["natalia alvarez", "es"],
  ["natalia moreno", "es"],
  ["natalia perez", "es"],
  ["natalia szymanski", "pl"],
  ["natalia tomaszewski", "pl"],
  ["natalia wojcik", "pl"],
  ["natarajan", "in"],
  ["nathalie", "fr"],
  ["nathalie aubry", "fr"],
  ["nathalie durand", "fr"],
  ["nathalie richard", "fr"],
  ["nathan", "fr"],
  ["nathan leclercq", "fr"],
  ["naufal", "ms"],
  ["naufal dahlan", "ms"],
  ["naufal latiff", "ms"],
  ["naufal nawawi", "ms"],
  ["navarro", "es"],
  ["naveen", "in"],
  ["naveen karandikar", "in"],
  ["naveen pandya", "in"],
  ["navya", "in"],
  ["navya cheema", "in"],
  ["navya subramanian", "in"],
  ["nawawi", "ms"],
  ["naz", "tr"],
  ["naz sahan", "tr"],
  ["naz ucar", "tr"],
  ["naz yetkin", "tr"],
  ["nazri", "ms"],
  ["nazri mohd", "ms"],
  ["nazri omar", "ms"],
  ["neha", "in"],
  ["neha banerjee", "in"],
  ["neha bhatia", "in"],
  ["nehir", "tr"],
  ["nehir bilgin", "tr"],
  ["nerea", "es"],
  ["nerea calvo", "es"],
  ["nerea diaz", "es"],
  ["nerea garcia", "es"],
  ["nesrin", "tr"],
  ["nesrin cakiroglu", "tr"],
  ["nesrin demirbas", "tr"],
  ["nesrin kaya", "tr"],
  ["nesrin yagiz", "tr"],
  ["nicolas", "fr"],
  ["nicolas roche", "fr"],
  ["nicole", "fr"],
  ["nicole girard", "fr"],
  ["nicole thomas", "fr"],
  ["nieto", "es"],
  ["nik", "ms"],
  ["nikhil", "in"],
  ["nikhil kalyanaraman", "in"],
  ["nikola", "pl"],
  ["nikola krawczyk", "pl"],
  ["nikola kruk", "pl"],
  ["nikola wawrzyniak", "pl"],
  ["nisha", "in"],
  ["nisha mukherjee", "in"],
  ["noel", "fr"],
  ["noelia", "es"],
  ["noelia franco", "es"],
  ["noelia moreno", "es"],
  ["noelia robles", "es"],
  ["noor", "ms"],
  ["nordin", "ms"],
  ["nowak", "pl"],
  ["nowakowski", "pl"],
  ["nowicki", "pl"],
  ["nunez", "es"],
  ["nur imran", "ms"],
  ["nur maarof", "ms"],
  ["nuria", "es"],
  ["nuria martinez", "es"],
  ["nuria soler", "es"],
  ["nurul", "ms"],
  ["nurul zin", "ms"],
  ["obeng", "ms"],
  ["oceane", "fr"],
  ["oceane benoit", "fr"],
  ["oceane lambert", "fr"],
  ["ojeda", "es"],
  ["okan", "tr"],
  ["olivier", "fr"],
  ["olivier caron", "fr"],
  ["olivier chevalier", "fr"],
  ["olivier martinez", "fr"],
  ["olivier pierre", "fr"],
  ["oliwia", "pl"],
  ["oliwia włodarczyk", "pl"],
  ["olszewski", "pl"],
  ["omar", "ms"],
  ["omer", "tr"],
  ["omer aslan", "tr"],
  ["omer ozbek", "tr"],
  ["ong", "ms"],
  ["onur", "tr"],
  ["onur kaplan", "tr"],
  ["onur topal", "tr"],
  ["ortega", "es"],
  ["ortiz", "es"],
  ["oscar", "es"],
  ["oscar ramirez", "es"],
  ["osman cakirca", "tr"],
  ["ostrowski", "pl"],
  ["othman", "ms"],
  ["othman bakar", "ms"],
  ["othman razak", "ms"],
  ["othman tajuddin", "ms"],
  ["othman wan", "ms"],
  ["owczarek", "pl"],
  ["ozan", "tr"],
  ["ozan koc", "tr"],
  ["ozbek", "tr"],
  ["ozcelik", "tr"],
  ["ozdemir", "tr"],
  ["ozen", "tr"],
  ["ozer", "tr"],
  ["ozge", "tr"],
  ["ozge toprak", "tr"],
  ["ozge yorulmaz", "tr"],
  ["ozgul", "tr"],
  ["ozgur", "tr"],
  ["ozisik", "tr"],
  ["ozkan", "tr"],
  ["ozkok", "tr"],
  ["ozturk", "tr"],
  ["pablo", "es"],
  ["pablo mata", "es"],
  ["pablo vera", "es"],
  ["pacheco", "es"],
  ["padma", "in"],
  ["padma bhagat", "in"],
  ["padma parikh", "in"],
  ["padma swaminathan", "in"],
  ["padmanabhan", "in"],
  ["paez", "es"],
  ["pai", "in"],
  ["pakhri", "ms"],
  ["palomo", "es"],
  ["pandey", "in"],
  ["pandya", "in"],
  ["pardo", "es"],
  ["pari", "in"],
  ["pari dhillon", "in"],
  ["pari raghavan", "in"],
  ["pari rajan", "in"],
  ["parikh", "in"],
  ["paris", "fr"],
  ["parra", "es"],
  ["parthasarathy", "in"],
  ["pascal", "fr"],
  ["pascal colin", "fr"],
  ["pascal pierre", "fr"],
  ["pascual", "es"],
  ["pastor", "es"],
  ["patel", "in"],
  ["patil", "in"],
  ["patricia blanc", "fr"],
  ["patricia soto", "es"],
  ["patrick", "fr"],
  ["patrycja", "pl"],
  ["patrycja gajda", "pl"],
  ["patryk", "pl"],
  ["patryk domanski", "pl"],
  ["patryk lewicki", "pl"],
  ["patryk michalak", "pl"],
  ["patryk nowak", "pl"],
  ["paul", "fr"],
  ["paul dupuy", "fr"],
  ["paul lemoine", "fr"],
  ["paul riviere", "fr"],
  ["paula", "es"],
  ["paula lozano", "es"],
  ["paula medina", "es"],
  ["paula vargas", "es"],
  ["paulina", "pl"],
  ["paulina mazurek", "pl"],
  ["pauline", "fr"],
  ["pauline giraud", "fr"],
  ["pawanchik", "ms"],
  ["pawar", "in"],
  ["paweł", "pl"],
  ["paweł baran", "pl"],
  ["paweł kołodziejczyk", "pl"],
  ["pawlak", "pl"],
  ["pawlik", "pl"],
  ["pawłowski", "pl"],
  ["payet", "fr"],
  ["pedro", "es"],
  ["pedro garcia", "es"],
  ["pedro mateo", "es"],
  ["pedro roman", "es"],
  ["pedro tomas", "es"],
  ["pelletier", "fr"],
  ["pena", "es"],
  ["pendek", "ms"],
  ["pereira", "es"],
  ["perrier", "fr"],
  ["perrin", "fr"],
  ["perrot", "fr"],
  ["pervin", "tr"],
  ["petit", "fr"],
  ["phadke", "in"],
  ["philippe", "fr"],
  ["philippe caron", "fr"],
  ["picard", "fr"],
  ["pierre", "fr"],
  ["pierre fournier", "fr"],
  ["pierre robert", "fr"],
  ["pietrzak", "pl"],
  ["pietrzyk", "pl"],
  ["pilar", "es"],
  ["pilar ramos", "es"],
  ["pillai", "in"],
  ["pinar", "tr"],
  ["pinar ozbek", "tr"],
  ["piotr", "pl"],
  ["piotr nowakowski", "pl"],
  ["piotrowski", "pl"],
  ["poirier", "fr"],
  ["polak", "pl"],
  ["polat", "tr"],
  ["ponce", "es"],
  ["pooja", "in"],
  ["pooja tandon", "in"],
  ["pranav", "in"],
  ["pranav bhagwat", "in"],
  ["pranav iyer", "in"],
  ["pranav kamath", "in"],
  ["pranav kulkarni", "in"],
  ["pranav rajput", "in"],
  ["pranav sen", "in"],
  ["prasad", "in"],
  ["prevost", "fr"],
  ["prieto", "es"],
  ["priya", "in"],
  ["priya pawar", "in"],
  ["priya rajan", "in"],
  ["priya sidhu", "in"],
  ["przybylski", "pl"],
  ["puteh", "ms"],
  ["puteri", "ms"],
  ["puteri che", "ms"],
  ["puteri ibrahim", "ms"],
  ["puteri rosli", "ms"],
  ["qasim", "ms"],
  ["qistina", "ms"],
  ["qistina hashim", "ms"],
  ["qistina kamal", "ms"],
  ["qistina sallehuddin", "ms"],
  ["quentin", "fr"],
  ["quentin caron", "fr"],
  ["quintana", "es"],
  ["rabia", "tr"],
  ["rabia kahraman", "tr"],
  ["radha", "in"],
  ["rafael", "es"],
  ["rafael soler", "es"],
  ["rafał", "pl"],
  ["rafał cieslak", "pl"],
  ["rafał owczarek", "pl"],
  ["rafał wisniewski", "pl"],
  ["raghavan", "in"],
  ["rahim", "ms"],
  ["rahim zainal", "ms"],
  ["rahim zakaria", "ms"],
  ["rahman", "ms"],
  ["rahul", "in"],
  ["rajan", "in"],
  ["rajesh", "in"],
  ["rajesh gill", "in"],
  ["rajesh nair", "in"],
  ["rajesh sood", "in"],
  ["rajput", "in"],
  ["raju", "in"],
  ["raju ghosh", "in"],
  ["raju narayanan", "in"],
  ["rakesh", "in"],
  ["rakesh parthasarathy", "in"],
  ["ramachandran", "in"],
  ["ramamurthy", "in"],
  ["raman", "in"],
  ["ramanujam", "in"],
  ["ramazan", "tr"],
  ["ramazan topaloglu", "tr"],
  ["ramazan yavuz", "tr"],
  ["ramesh", "in"],
  ["ramirez", "es"],
  ["ramon", "es"],
  ["ramon cano", "es"],
  ["ramos", "es"],
  ["ranganathan", "in"],
  ["rania", "ms"],
  ["rania azlan", "ms"],
  ["rania mansor", "ms"],
  ["rao", "in"],
  ["raphael", "fr"],
  ["raphael lemoine", "fr"],
  ["raquel", "es"],
  ["raquel espinosa", "es"],
  ["raquel ponce", "es"],
  ["raquel roca", "es"],
  ["rashid", "ms"],
  ["rauf", "ms"],
  ["raul", "es"],
  ["raul crespo", "es"],
  ["raul maldonado", "es"],
  ["rayyan", "ms"],
  ["rayyan majid", "ms"],
  ["razak", "ms"],
  ["razak hashim", "ms"],
  ["razak jais", "ms"],
  ["razak sulaiman", "ms"],
  ["recep", "tr"],
  ["recep kilic", "tr"],
  ["recep ozcelik", "tr"],
  ["reddy", "in"],
  ["rekha", "in"],
  ["remy", "fr"],
  ["renard", "fr"],
  ["renata", "pl"],
  ["renata wasilewski", "pl"],
  ["renata ziołkowski", "pl"],
  ["renaud", "fr"],
  ["renault", "fr"],
  ["rene", "fr"],
  ["rene dubois", "fr"],
  ["rene gaillard", "fr"],
  ["rene germain", "fr"],
  ["rene paris", "fr"],
  ["rene pelletier", "fr"],
  ["reyansh", "in"],
  ["reyansh dave", "in"],
  ["reyansh goyal", "in"],
  ["reyes", "es"],
  ["richard", "fr"],
  ["ridzuan", "ms"],
  ["rios", "es"],
  ["rivas", "es"],
  ["rivera", "es"],
  ["riviere", "fr"],
  ["riya", "in"],
  ["riya mahadevan", "in"],
  ["riya thakur", "in"],
  ["robert", "fr"],
  ["robert dufour", "fr"],
  ["roberto", "es"],
  ["roberto alonso", "es"],
  ["roberto rodriguez", "es"],
  ["roberto rojas", "es"],
  ["robin", "fr"],
  ["robles", "es"],
  ["roca", "es"],
  ["roche", "fr"],
  ["rocio", "es"],
  ["rocio alvarez", "es"],
  ["rocio navarro", "es"],
  ["rocio pereira", "es"],
  ["rocio roman", "es"],
  ["rocio velasco", "es"],
  ["rodriguez", "es"],
  ["roger", "fr"],
  ["roger bailly", "fr"],
  ["roger carpentier", "fr"],
  ["roger petit", "fr"],
  ["rohan", "in"],
  ["rohan sawant", "in"],
  ["rojas", "es"],
  ["roldan", "es"],
  ["rolland", "fr"],
  ["romain", "fr"],
  ["romain julien", "fr"],
  ["roman kazmierczak", "pl"],
  ["roman mucha", "pl"],
  ["roman owczarek", "pl"],
  ["roman piotrowski", "pl"],
  ["romero", "es"],
  ["rosa", "es"],
  ["rosa cruz", "es"],
  ["roslan", "ms"],
  ["rosli", "ms"],
  ["rousseau", "fr"],
  ["roussel", "fr"],
  ["roux", "fr"],
  ["royer", "fr"],
  ["ruben", "es"],
  ["ruben hidalgo", "es"],
  ["ruben lorenzo", "es"],
  ["rubio", "es"],
  ["ruiz", "es"],
  ["rutkowski", "pl"],
  ["ryszard", "pl"],
  ["ryszard szczepanski", "pl"],
  ["saad", "ms"],
  ["saanvi", "in"],
  ["sabrina", "ms"],
  ["sabrina baharin", "ms"],
  ["sabrina effendi", "ms"],
  ["sabrina ghani", "ms"],
  ["sabrina razak", "ms"],
  ["sabrina samad", "ms"],
  ["sadowski", "pl"],
  ["saez", "es"],
  ["sahan", "tr"],
  ["sahin", "tr"],
  ["salas", "es"],
  ["salazar", "es"],
  ["salleh", "ms"],
  ["sallehuddin", "ms"],
  ["salvador", "es"],
  ["salvador espinosa", "es"],
  ["salvador lozano", "es"],
  ["salvador luna", "es"],
  ["salvador maldonado", "es"],
  ["samad", "ms"],
  ["sameer", "in"],
  ["sandhu", "in"],
  ["sandra majewski", "pl"],
  ["sandra moya", "es"],
  ["sandra ponce", "es"],
  ["sandra rivas", "es"],
  ["sandra stepien", "pl"],
  ["sandrine", "fr"],
  ["sandrine leclercq", "fr"],
  ["sane", "in"],
  ["sangeeta", "in"],
  ["sangeeta bhatia", "in"],
  ["sangeeta chandrasekaran", "in"],
  ["sangeeta chatterjee", "in"],
  ["sangeeta dave", "in"],
  ["sangeeta singh", "in"],
  ["sani", "ms"],
  ["sanjay", "in"],
  ["sanjay apte", "in"],
  ["sanjay bains", "in"],
  ["sanjay rao", "in"],
  ["sanjay sinha", "in"],
  ["santana", "es"],
  ["santiago", "es"],
  ["santos", "es"],
  ["sanz", "es"],
  ["sapna", "in"],
  ["sapuan", "ms"],
  ["sara", "es"],
  ["sara carmona", "es"],
  ["sara prieto", "es"],
  ["sara vera", "es"],
  ["sarac", "tr"],
  ["sarah", "fr"],
  ["sarah carre", "fr"],
  ["sari", "tr"],
  ["sarikaya", "tr"],
  ["sarioglu", "tr"],
  ["sawant", "in"],
  ["sawicki", "pl"],
  ["saxena", "in"],
  ["schmitt", "fr"],
  ["schneider", "fr"],
  ["sebastian", "pl"],
  ["sebastian markowski", "pl"],
  ["sebastian mucha", "pl"],
  ["sebastian sieradzki", "pl"],
  ["sebastien", "fr"],
  ["sebastien rousseau", "fr"],
  ["seda", "tr"],
  ["seda tas", "tr"],
  ["sekhon", "in"],
  ["selim", "tr"],
  ["selin", "tr"],
  ["selin kurnaz", "tr"],
  ["selvam", "in"],
  ["selvam roy", "in"],
  ["sema", "tr"],
  ["sema gumus", "tr"],
  ["senturk", "tr"],
  ["sergio", "es"],
  ["serife", "tr"],
  ["serife bayram", "tr"],
  ["serife camlica", "tr"],
  ["serife sahan", "tr"],
  ["serkan", "tr"],
  ["serkan gul", "tr"],
  ["serkan kahraman", "tr"],
  ["serkan kaya", "tr"],
  ["serkan komur", "tr"],
  ["serrano", "es"],
  ["sethi", "in"],
  ["sevgi", "tr"],
  ["sevgi erdem", "tr"],
  ["sevgi karadag", "tr"],
  ["seyma", "tr"],
  ["seyma ozen", "tr"],
  ["sezer", "tr"],
  ["shafiq", "ms"],
  ["shafiq yatim", "ms"],
  ["shafiq zainal", "ms"],
  ["shah", "in"],
  ["shanti", "in"],
  ["shanti krishnamurthy", "in"],
  ["shariff", "ms"],
  ["sharma", "in"],
  ["shaurya", "in"],
  ["shaurya iyer", "in"],
  ["shaurya malhotra", "in"],
  ["shetty", "in"],
  ["shinde", "in"],
  ["shreya", "in"],
  ["shreya sundaram", "in"],
  ["shreya thakkar", "in"],
  ["siddharth", "in"],
  ["siddharth mann", "in"],
  ["siddharth mishra", "in"],
  ["siddharth swaminathan", "in"],
  ["sidhu", "in"],
  ["sienkiewicz", "pl"],
  ["sieradzki", "pl"],
  ["sierra", "es"],
  ["sikora", "pl"],
  ["sikorski", "pl"],
  ["silva", "es"],
  ["silvia", "es"],
  ["silvia medina", "es"],
  ["silvia pastor", "es"],
  ["silvia santiago", "es"],
  ["silvia santos", "es"],
  ["silvia serrano", "es"],
  ["simon", "fr"],
  ["simone", "fr"],
  ["simone perez", "fr"],
  ["simsek", "tr"],
  ["sinan", "tr"],
  ["sinan eren", "tr"],
  ["singh", "in"],
  ["sinha", "in"],
  ["sita", "in"],
  ["sita joshi", "in"],
  ["sita rajput", "in"],
  ["sita thyagarajan", "in"],
  ["siti", "ms"],
  ["siti hanafi", "ms"],
  ["siti yaacob", "ms"],
  ["skowronski", "pl"],
  ["sneha", "in"],
  ["sneha bhagwat", "in"],
  ["sneha bhardwaj", "in"],
  ["sobanski", "pl"],
  ["sobczak", "pl"],
  ["sobolewski", "pl"],
  ["sodhi", "in"],
  ["sofia bravo", "es"],
  ["sofia conde", "es"],
  ["sofia dahlan", "ms"],
  ["sofia mendez", "es"],
  ["sofia prieto", "es"],
  ["sofia roslan", "ms"],
  ["sofia suarez", "es"],
  ["sokołowski", "pl"],
  ["soler", "es"],
  ["sonmez", "tr"],
  ["sood", "in"],
  ["sophie", "fr"],
  ["sosnowski", "pl"],
  ["soto", "es"],
  ["sowa", "pl"],
  ["soylu", "tr"],
  ["soysal", "tr"],
  ["sołtys", "pl"],
  ["srinivasan", "in"],
  ["srivastava", "in"],
  ["stanisław", "pl"],
  ["stanisław klimek", "pl"],
  ["stanisława", "pl"],
  ["stanisława lis", "pl"],
  ["stankiewicz", "pl"],
  ["stephane", "fr"],
  ["stephane denis", "fr"],
  ["stephanie", "fr"],
  ["stephanie henry", "fr"],
  ["stephanie joly", "fr"],
  ["stepien", "pl"],
  ["su", "tr"],
  ["su keskin", "tr"],
  ["suarez", "es"],
  ["subramanian", "in"],
  ["sulaiman", "ms"],
  ["suleyman", "tr"],
  ["suleyman tuncel", "tr"],
  ["sultan", "tr"],
  ["sultan cakal", "tr"],
  ["sultan demiroz", "tr"],
  ["sundaram", "in"],
  ["sundararajan", "in"],
  ["sunil", "in"],
  ["sunil roy", "in"],
  ["sunita", "in"],
  ["suresh", "in"],
  ["suresh verma", "in"],
  ["suzanne", "fr"],
  ["suzanne garcia", "fr"],
  ["suzanne noel", "fr"],
  ["swaminathan", "in"],
  ["swati", "in"],
  ["swati bains", "in"],
  ["swati natarajan", "in"],
  ["syafiq", "ms"],
  ["syafiq wan", "ms"],
  ["sylviane", "fr"],
  ["sylvie", "fr"],
  ["sylwia", "pl"],
  ["szczepaniak", "pl"],
  ["szczepanski", "pl"],
  ["szczesny", "pl"],
  ["szewczyk", "pl"],
  ["szulc", "pl"],
  ["szymanski", "pl"],
  ["szymon", "pl"],
  ["szymon kaczmarczyk", "pl"],
  ["szymon nowicki", "pl"],
  ["tadeusz", "pl"],
  ["tadeusz kaczmar", "pl"],
  ["tadeusz kubiak", "pl"],
  ["tadeusz urbanski", "pl"],
  ["tahir", "ms"],
  ["tahir ali", "ms"],
  ["tahir kassim", "ms"],
  ["tahir marican", "ms"],
  ["tajuddin", "ms"],
  ["talib", "ms"],
  ["tan", "ms"],
  ["tandon", "in"],
  ["tanvi", "in"],
  ["tanvi jain", "in"],
  ["tara", "in"],
  ["tara srivastava", "in"],
  ["tarik", "tr"],
  ["tarik aytemiz", "tr"],
  ["tarik duman", "tr"],
  ["tarmizi", "ms"],
  ["tarmizi nawawi", "ms"],
  ["tarmizi wan", "ms"],
  ["tas", "tr"],
  ["tekin", "tr"],
  ["tengku", "ms"],
  ["teresa krupa", "pl"],
  ["teresa maciejewski", "pl"],
  ["thakkar", "in"],
  ["thakur", "in"],
  ["theo", "fr"],
  ["theo giraud", "fr"],
  ["thierry", "fr"],
  ["thierry dumont", "fr"],
  ["thomas", "fr"],
  ["thomas colin", "fr"],
  ["thyagarajan", "in"],
  ["tiwari", "in"],
  ["toker", "tr"],
  ["tolga", "tr"],
  ["tolga arslan", "tr"],
  ["tolga ozdemir", "tr"],
  ["tomas", "es"],
  ["tomas carrillo", "es"],
  ["tomas delgado", "es"],
  ["tomas molina", "es"],
  ["tomasz", "pl"],
  ["tomaszewski", "pl"],
  ["tomczak", "pl"],
  ["toor", "in"],
  ["topal", "tr"],
  ["topaloglu", "tr"],
  ["topcu", "tr"],
  ["toprak", "tr"],
  ["torres", "es"],
  ["tosun", "tr"],
  ["tracz", "pl"],
  ["trivedi", "in"],
  ["trujillo", "es"],
  ["tugba", "tr"],
  ["tugba yavuz", "tr"],
  ["tulay", "tr"],
  ["tulay can", "tr"],
  ["tulay ozgur", "tr"],
  ["tunc", "tr"],
  ["tuncel", "tr"],
  ["turan", "tr"],
  ["turk", "tr"],
  ["ucar", "tr"],
  ["uda", "ms"],
  ["ugur", "tr"],
  ["ugur kus", "tr"],
  ["ugur tekin", "tr"],
  ["ujang", "ms"],
  ["umar", "ms"],
  ["umar hamid", "ms"],
  ["umran", "tr"],
  ["umran bilgin", "tr"],
  ["umran demir", "tr"],
  ["umran kurnaz", "tr"],
  ["umran turan", "tr"],
  ["unal", "tr"],
  ["urbanski", "pl"],
  ["urszula", "pl"],
  ["urszula cieslak", "pl"],
  ["urszula dudek", "pl"],
  ["urszula szczepanski", "pl"],
  ["usha", "in"],
  ["usha mehta", "in"],
  ["usha raghavan", "in"],
  ["usha verma", "in"],
  ["usman", "ms"],
  ["vaidyanathan", "in"],
  ["vaishnavi", "in"],
  ["vaishnavi goyal", "in"],
  ["vaishnavi kumar", "in"],
  ["valerie", "fr"],
  ["valerie barbier", "fr"],
  ["valerie gaillard", "fr"],
  ["vallejo", "es"],
  ["vandana", "in"],
  ["vandana bhattacharya", "in"],
  ["vandana chatterjee", "in"],
  ["vargas", "es"],
  ["varun", "in"],
  ["varun thakur", "in"],
  ["vasquez", "es"],
  ["vasseur", "fr"],
  ["vazquez", "es"],
  ["veena", "in"],
  ["veena patel", "in"],
  ["vega", "es"],
  ["vela", "es"],
  ["velasco", "es"],
  ["venkat", "in"],
  ["venkataraman", "in"],
  ["venkatesan", "in"],
  ["vera", "es"],
  ["verma", "in"],
  ["veronica", "es"],
  ["veronica cano", "es"],
  ["veronica vicente", "es"],
  ["veronique", "fr"],
  ["veronique gerard", "fr"],
  ["veronique guillot", "fr"],
  ["veronique paris", "fr"],
  ["vicente", "es"],
  ["victor", "es"],
  ["vihaan", "in"],
  ["vihaan iyengar", "in"],
  ["vijay", "in"],
  ["vijay bansal", "in"],
  ["vijay grewal", "in"],
  ["vikram", "in"],
  ["vikram gokhale", "in"],
  ["vikram iyer", "in"],
  ["vila", "es"],
  ["vildan", "tr"],
  ["vildan erdogan", "tr"],
  ["vincent", "fr"],
  ["vincent colin", "fr"],
  ["vincent girard", "fr"],
  ["vincent laurent", "fr"],
  ["virginie", "fr"],
  ["virginie charpentier", "fr"],
  ["vishwanathan", "in"],
  ["vivaan", "in"],
  ["vivaan jain", "in"],
  ["vivaan raghavan", "in"],
  ["volkan", "tr"],
  ["volkan dogan", "tr"],
  ["vora", "in"],
  ["wahab", "ms"],
  ["wahab wahyu", "ms"],
  ["wahid", "ms"],
  ["wahyu", "ms"],
  ["walczak", "pl"],
  ["wan", "ms"],
  ["wanda", "pl"],
  ["wani", "ms"],
  ["wani qasim", "ms"],
  ["wardina", "ms"],
  ["wardina iliyas", "ms"],
  ["wasilewski", "pl"],
  ["wati", "ms"],
  ["wawrzyniak", "pl"],
  ["weronika", "pl"],
  ["wieczorek", "pl"],
  ["wieczorkiewicz", "pl"],
  ["wiesław", "pl"],
  ["wiesław czerwinski", "pl"],
  ["wiesław konieczny", "pl"],
  ["wiesława", "pl"],
  ["wiesława marek", "pl"],
  ["wiesława zalewski", "pl"],
  ["wiktor", "pl"],
  ["wiktor marek", "pl"],
  ["wiktoria", "pl"],
  ["wiktoria rutkowski", "pl"],
  ["wilk", "pl"],
  ["wisniewska", "pl"],
  ["wisniewski", "pl"],
  ["witkowski", "pl"],
  ["wojciech", "pl"],
  ["wojciech stankiewicz", "pl"],
  ["wojciechowski", "pl"],
  ["wojcik", "pl"],
  ["wozniak", "pl"],
  ["wrobel", "pl"],
  ["wroblewska", "pl"],
  ["wroblewski", "pl"],
  ["wysocki", "pl"],
  ["władysław", "pl"],
  ["władysław sawicki", "pl"],
  ["włodarczyk", "pl"],
  ["yaacob", "ms"],
  ["yaakob", "ms"],
  ["yadav", "in"],
  ["yagci", "tr"],
  ["yagcilar", "tr"],
  ["yagiz", "tr"],
  ["yagmur", "tr"],
  ["yahya", "ms"],
  ["yakub", "ms"],
  ["yalcin", "tr"],
  ["yasemin", "tr"],
  ["yasemin bayram", "tr"],
  ["yasemin cetiner", "tr"],
  ["yasemin cevik", "tr"],
  ["yasemin erdem", "tr"],
  ["yasemin turk", "tr"],
  ["yash", "in"],
  ["yasmin", "ms"],
  ["yasmin fikri", "ms"],
  ["yasmin yakub", "ms"],
  ["yatim", "ms"],
  ["yavuz", "tr"],
  ["yeliz", "tr"],
  ["yeliz caki", "tr"],
  ["yeliz camlica", "tr"],
  ["yeliz ozgur", "tr"],
  ["yeliz sarac", "tr"],
  ["yetkin", "tr"],
  ["yigit", "tr"],
  ["yigit colak", "tr"],
  ["yildan", "tr"],
  ["yildirim", "tr"],
  ["yildiz", "tr"],
  ["yilmaz", "tr"],
  ["yolanda", "es"],
  ["yolanda carvajal", "es"],
  ["yoruk", "tr"],
  ["yorulmaz", "tr"],
  ["yuksel", "tr"],
  ["yunus", "ms"],
  ["yusof", "ms"],
  ["yusof ghani", "ms"],
  ["yusuf", "tr"],
  ["yusuf akkaya", "tr"],
  ["yusuf eren", "tr"],
  ["yusuf karaca", "tr"],
  ["yusuf tosun", "tr"],
  ["yvette", "fr"],
  ["zabidi", "ms"],
  ["zahari", "ms"],
  ["zahra", "ms"],
  ["zahra halim", "ms"],
  ["zahra wati", "ms"],
  ["zahra yusof", "ms"],
  ["zaid", "ms"],
  ["zaid bakar", "ms"],
  ["zaid hamzah", "ms"],
  ["zaid osman", "ms"],
  ["zainab", "ms"],
  ["zainab zahari", "ms"],
  ["zainal", "ms"],
  ["zajac", "pl"],
  ["zakaria", "ms"],
  ["zaki", "ms"],
  ["zaki arshad", "ms"],
  ["zaki dollah", "ms"],
  ["zakrzewski", "pl"],
  ["zalewski", "pl"],
  ["zamri", "ms"],
  ["zawadzki", "pl"],
  ["zbigniew", "pl"],
  ["zbigniew kazmierczak", "pl"],
  ["zbigniew tomaszewski", "pl"],
  ["zdzisław", "pl"],
  ["zdzisław kaminski", "pl"],
  ["zehra", "tr"],
  ["zehra kahraman", "tr"],
  ["zehra komur", "tr"],
  ["zehra ozen", "tr"],
  ["zehra yalcin", "tr"],
  ["zehra yavuz", "tr"],
  ["zeliha", "tr"],
  ["zeynep", "tr"],
  ["zeynep arslan", "tr"],
  ["zeynep gul", "tr"],
  ["zeynep karaca", "tr"],
  ["zeynep ozdemir", "tr"],
  ["zeynep ozisik", "tr"],
  ["zieba", "pl"],
  ["zielinski", "pl"],
  ["zikri", "ms"],
  ["zikri halim", "ms"],
  ["zikri majid", "ms"],
  ["zin", "ms"],
  ["ziołkowski", "pl"],
  ["zofia", "pl"],
  ["zofia borkowski", "pl"],
  ["zofia kruk", "pl"],
  ["zofia maj", "pl"],
  ["zofia tomczak", "pl"],
  ["zuzanna", "pl"],
  ["zuzanna jasinski", "pl"],
  ["zuzanna kaczmarek", "pl"],
  ["zuzanna ostrowski", "pl"],
  ["zuzia", "pl"],
  ["zuzia majewski", "pl"],
  ["zuzia marek", "pl"],
  ["łukasz", "pl"],
  ["łukasz nowak", "pl"],
  ["łukasz tomczak", "pl"],
]);
